### ISSUE TITLE
Kérdés

### ISSUE THREAD

**Issue by kovacsmarcell** [jobua/erettsegi-cpp#1]
Azt szeretném megkérdezni, milyen compiler-t ajánlasz C++hoz érettségihez, otthon Visual Studio 2015-öt használok, de az érettségin csak Visual Studio 2013 Express-t lehet használni, az megteszi a célnak?

**Comment by jobua** [comment]
A Visual Studio jó választás, és érdemes ugyanazon a verzión gyakorolni, ami az érettségin is lesz.
